### ISSUE TITLE
【BUG】首页最后一个板块里的新建页面和最新更改无法打开

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/Moegirl-plus#1]
点击后显示页面不存在QAQ

**Comment by koharubiyori** [comment]
研究了一下，由于mw没提供检测标题是否可以创建的接口，新建页面暂时不能做；首页底部最新更改那里也有些问题，可以强行实现，但如果未来萌百样式有调整很有可能导致出现未知错误，所以也做不了_(:з」∠)_，改成弹出提示了
