### ISSUE TITLE
利用DDoS实现H萌娘直连

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/Moegirl-plus#2]
![微信图片_20210203205600](https://user-images.githubusercontent.com/59795360/106750077-51322100-6662-11eb-86cb-792493167124.jpg)

**Comment by koharubiyori** [comment]
151.101.65.6，104.16.124.96，是这两个ip吗，第一个无法访问，第二个在访问的时候都提示“Error 1003 Direct IP access not allowed”

**Comment by 850710247liu** [comment]
不是通过 IP 访问，要在程序里把 hmoegirl.org 指向这些 IP
第一个 151.101 的不是 Cloudflare 的 IP

**Comment by 850710247liu** [comment]
是下面 Cloudflare 的那两个

**Comment by ygsk10** [comment]
https://github.com/dart-lang/http/issues/222

**Comment by koharubiyori** [comment]
> [dart-lang/http#222](https://github.com/dart-lang/http/issues/222)
> 
> 看来还得自己写 dns 部分，像 pixiv-flutter 那样
> 
> https://github.com/Notsfsssf/pixez-flutter/blob/632704cf712a06e873947da2b9564dc4fcad3e47/lib/network/onezero_client.dart

做了一些尝试，这个方法应该是不行，自定义dns只是解决因dns污染导致的被墙，并不能绕过H萌娘本身的ddos防火墙。另外我发现pixiv-flutter中只是通过直接请求Cloudflare来获取ip然后拼链接，并没有实现自定义dns。[dart-lang/sdk#36551](https://github.com/dart-lang/sdk/issues/36551)这里也说目前并没有提供自定义dns的api。我大致搜索了一下，好像andorid自定义dns是需要root权限的，不过也不能确定，我不了解android开发。另外我又在挂着梯子的情况下用postman模拟了一下：
``` curl
curl --location --request GET '104.16.124.96' \
--header 'Host: www.hmoegirl.com' \
--header 'Referer: https://www.hmoegirl.com' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.151 Safari/537.36'
```
结果是报`Error: Protocol "https:" not supported. Expected "http:"`。

**Comment by ygsk10** [comment]
> pixiv-flutter中只是通过直接请求Cloudflare来获取ip然后拼链接

抱歉，忽略了这一点。

Pixiv 是可以直接通过 IP 访问的， 但是 hmoegirl 不可以。

> 另外我又在挂着梯子的情况下用postman模拟了一下

这一步应该这样写
```
curl --location --request GET 'https://104.16.124.96' \
--header 'Host: www.hmoegirl.com' \
--header 'Referer: https://www.hmoegirl.com' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.151 Safari/537.36'
```
然后会收到 Cloudflare 的 403

---

这样是可以的，但是会收到 js 质询的页面（503）

```
curl -I \
https://www.hmoegirl.com \
--connect-to www.hmoegirl.com:443:104.16.124.96
```

**Comment by 850710247liu** [comment]
现在取消JS质询了 还可以直连吗
