### ISSUE TITLE
几个比较严重的BUG

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/Moegirl-plus#7]
+彩色黑幕无法通过点击刮开
+底部到其他WIKI模板被使用了两次
如在APP上访问缘之空条目可发现这些问题。
编辑记录显示的增减数字只是最后一次的，希望他能像桌面端那种相加起来的
另外希望大佬把用户贡献页加到侧边栏里，它其实很重要
辛苦了

**Comment by 850710247liu** [comment]
[[special:差异/这里是数字]]
希望适配一下这个特殊链接，咱们不是已经有对比图吗..能跳转一下最好了

**Comment by koharubiyori** [comment]
> +彩色黑幕无法通过点击刮开
> +底部到其他WIKI模板被使用了两次
> 如在APP上访问缘之空条目可发现这些问题。
> 编辑记录显示的增减数字只是最后一次的，希望他能像桌面端那种相加起来的
> 另外希望大佬把用户贡献页加到侧边栏里，它其实很重要
> 辛苦了

已修改

**Comment by koharubiyori** [comment]
> [[special:差异/这里是数字]]
> 希望适配一下这个特殊链接，咱们不是已经有对比图吗..能跳转一下最好了

这个等到重构之后吧
